### ISSUE TITLE
Unable to crosscompile for raspberry pi 3

### ISSUE THREAD

**Issue by ChristopheBelpaire** [arjan/nerves_io_nfc#1]
Hello, I'm trying to use this library with nerves, and I have some compilation problems on mac os.
When I try to compile the library with : 
`NERVES_TARGET=rpi3 MAKE_HOST=arm-unknown-linux-gnu mix compile nerves_io_nfc` 
it fails with:
 `/Users/christophebelpaire/selinko/indus/_build/rpi3/dev/nerves/toolchain/bin/arm-unknown-linux-gnueabihf-gcc -c -I/Users/christophebelpaire/selinko/indus/_build/rpi3/dev/nerves/system/staging/usr/lib/erlang/erts-8.0/include -I/Users/christophebelpaire/selinko/indus/_build/rpi3/dev/nerves/system/staging/usr/lib/erlang/lib/erl_interface-3.9/include -O2 -Wall -Wextra -Wno-unused-parameter -I/Users/christophebelpaire/selinko/indus/target/include -o src/main.o src/main.c
/Users/christophebelpaire/selinko/indus/_build/rpi3/dev/nerves/toolchain/bin/arm-unknown-linux-gnueabihf-gcc src/main.o -L/Users/christophebelpaire/selinko/indus/_build/rpi3/dev/nerves/system/staging/usr/lib/erlang/erts-8.0/lib -L/Users/christophebelpaire/selinko/indus/_build/rpi3/dev/nerves/system/staging/usr/lib/erlang/lib/erl_interface-3.9/lib -lerts -lerl_interface -lei -L/Users/christophebelpaire/selinko/indus/target/lib -lnfc -lusb -static -o priv/nfc_poller
/Users/christophebelpaire/selinko/indus/target/lib/libnfc.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [priv/nfc_poller] Error 1`

Any idea how to fix this ?
Thanks in advance!

**Comment by arjan** [comment]
Is this from a clean checkout?
It seems to me that one of the libraries is not cross-compiled.
can you run: `file /Users/christophebelpaire/selinko/indus/target/lib/libnfc.a`
to see if it indeed has an ARM target and not x86?

**Comment by ChristopheBelpaire** [comment]
It returns : `file /Users/christophebelpaire/selinko/indus/target/lib/libnfc.a
/Users/christophebelpaire/selinko/indus/target/lib/libnfc.a: current ar archive`

**Comment by ChristopheBelpaire** [comment]
If I compile and use on the raspberry it works  btw :)

**Comment by arjan** [comment]
That's how it's supposed to work yes.
On linux it should also work. Make sure you compile everything cleanly when you switch build targets.

**Comment by ChristopheBelpaire** [comment]
It seems that it tries to link with the wrong library maybe :
`/home/runner/app/_build/rpi3/dev/nerves/toolchain/bin/../lib/gcc/arm-unknown-linux-gnueabihf/4.9.3/../../../../arm-unknown-linux-gnueabihf/bin/ld.bfd: skipping incompatible /usr/lib/x86_64-linux-gnu/libc.so when searching for -lc
/usr/lib/x86_64-linux-gnu/libc.a: error adding symbols: File format not recognized`

It use : `/usr/lib/x86_64-linux-gnu/libc.so`.
Maybe it is the problem ?

**Comment by arjan** [comment]
That's indeed wrong. Weird.. I always have been cross-compiling this for RPi, never even tried compiling it _on_ the RPi.

**Comment by ChristopheBelpaire** [comment]
I made a test project here : https://github.com/ChristopheBelpaire/test_nerves_nfc
It fail to compile on osx with :
```
In file included from nfc-emulate-forum-tag4.c:70:0:
/Users/christophebelpaire/selinko/test_nerves_nfc/_build/rpi3/dev/nerves/system/staging/usr/include/stdint.h:49:28: warning: redefinition of typedef 'uint16_t' [-Wpedantic]
 typedef unsigned short int uint16_t;
                            ^
<command-line>:0:11: note: previous declaration of 'uint16_t' was here
/Users/christophebelpaire/selinko/test_nerves_nfc/_build/rpi3/dev/nerves/system/staging/usr/include/sys/types.h:190:24: note: in expansion of macro 'u_int16_t'
   typedef unsigned int u_int##N##_t __attribute__ ((__mode__ (MODE)))
                        ^
/Users/christophebelpaire/selinko/test_nerves_nfc/_build/rpi3/dev/nerves/system/staging/usr/include/sys/types.h:201:1: note: in expansion of macro '__u_intN_t'
 __u_intN_t (16, __HI__);
 ^
  CCLD   nfc-emulate-forum-tag4
nfc-emulate-forum-tag4.o: In function `nfcforum_tag4_io':
nfc-emulate-forum-tag4.c:(.text+0x34): undefined reference to `print_hex'
nfc-emulate-forum-tag4.c:(.text+0x2fc): undefined reference to `print_hex'
collect2: error: ld returned 1 exit status
make[3]: *** [nfc-emulate-forum-tag4] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [libnfc] Error 2
```

**Comment by arjan** [comment]
Thanks, I'll give it a spin tomorrow on my mac.

**Comment by rossbeale** [comment]
Bit late to the party but having the same issue - was there a solution for this or another way to cross compile?

**Comment by arjan** [comment]
I'm not really sure what the status was, sorry. I don't think I tried it on my mac in the end.
